# Generated by Django 4.0.6 on 2022-07-30 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('med_fhv', models.DecimalField(decimal_places=6, default=0, max_digits=30, verbose_name='median first hour view')),
            ],
            options={
                'db_table': 'channels',
            },
        ),
        migrations.CreateModel(
            name='ScrapedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=64)),
                ('video_id', models.CharField(max_length=64)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField()),
                ('views', models.BigIntegerField()),
                ('processed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'scrapped_data',
            },
        ),
    ]
